### ISSUE TITLE
If the exercise has `learnpack_deploy_url` you should open it in the cloud

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7956]
In the public view of exercises

 - [ ] If the exercise has `asset.learnpack_deploy_url`, then you should show a button that says `Start interactive exercise` (Remove the one that says open with LearnPack and clone it locally), showing only one button.

![Screenshot 2024-11-06 at 4 49 44 PM](https://github.com/user-attachments/assets/71858e27-6e3b-4bea-a241-e977830d1264)

**Comment by lumi-tip** [comment]
I think this bug is already fixed 👍

**Comment by tommygonzaleza** [comment]
- [ ] Start exercise should be uppercase
![Screenshot 2024-11-07 at 10 54 35 AM](https://github.com/user-attachments/assets/5e5b4005-defa-4dc3-814f-fa45ade02323)

**Comment by WinstonLesuT** [comment]
When the language is set as **EN** it still shows the two buttons. 
<img width="951" alt="Screenshot 2024-11-07 110358" src="https://github.com/user-attachments/assets/52327741-517b-406a-a6a7-0ea7be2cc1d7">

But when the language is set as **ES** it shows the correct button. 
<img width="954" alt="Screenshot 2024-11-07 110423" src="https://github.com/user-attachments/assets/a0c9ea5f-cd82-453f-ba4e-688521001eb0">

Is this something that you are still working on it?

**Comment by lumi-tip** [comment]
This may happen because the asset in spanish has learnpack_deploy_url whereas in english it doesn't 🦀
